# Generated by Django 4.1.3 on 2022-11-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_comment_post_alter_like_post_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='isLiked',
            field=models.BooleanField(default=True),
        ),
    ]
