# Generated by Django 4.1.3 on 2022-11-15 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_profile_bio_profile_mobile_profile_propic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
